## Gradle JVM / build environment

# Increase JVM heap and Metaspace for R8 release minification.
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8 -Djava.awt.headless=true -XX:+UseParallelGC

# Kotlin compiler daemon
kotlin.daemon.jvmargs=-Xmx4g -Dfile.encoding=UTF-8 -Djava.awt.headless=true

# Android
android.useAndroidX=true
android.enableJetifier=false
android.nonTransitiveRClass=false

# Gradle configuration
org.gradle.configuration-cache=true
org.gradle.unsafe.configuration-cache=true
org.gradle.configuration-cache.problems=warn
org.gradle.ide.support.future.agp.versions=true

# Build performance
org.gradle.parallel=false
org.gradle.daemon=true
org.gradle.configureondemand=false
org.gradle.workers.max=2

# Suppress deprecated warnings
android.suppressUnsupportedOptionWarnings=android.suppressUnsupportedOptionWarnings,android.nonFinalResIds

# JitPack / NewPipeExtractor download timeouts
systemProp.org.gradle.internal.http.connectionTimeout=180000
systemProp.org.gradle.internal.http.socketTimeout=180000

# Dependency caching
org.gradle.caching=false

# KSP
ksp.incremental=false
